### ISSUE TITLE
Free shipping on J2 Store 

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#100]
Suppose we have products that are supposed to be shipped free of charge for 15 days in time for Christmas, and after this date it will return to the previous routine and the shipping costs will be calculated.
**This is different from the discount code**
**tip :**
After the product is added to the shopping cart and the shipping method is selected, the shipping fee will be calculated as 0, and of course, there will be a notification on this page that the shipping fee is 0.
Currently, is there a possibility to do such a method, it means automatic application and not through a discount code

**Comment by mgopin3** [comment]
@sajadsheikhy I understand your concern. At the moment, we regret to inform you that our J2Store component is provided free of charge, and therefore, we do not offer custom development or support for such features. Our current focus is on migrating all plugins to be compatible with J2Store4. Consequently, we are only able to provide support for these plugins. Unfortunately, we do not have a feature that automatically applies free shipping based on time duration or displays shipping notifications during checkout. However, please rest assured that we value your feedback, and we will duly consider incorporating this feature into future releases of J2Store. Thank you for your understanding.

Note:- Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by sajadsheikhy** [comment]
Thanks to you and the support team of j2store

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
