### ISSUE TITLE
Languages for J2 Store

### ISSUE THREAD

**Issue by ufuk-avcu** [J2Store4/j2store4#103]
Where are the Language Packs for J2 Store V4?

**Comment by mgopin3** [comment]
@ufuk-avcu We would like to inform you that currently, we only have language availability for J2Store3. Please rest assured that we appreciate your feedback, and we are actively working on making languages available for all countries. As soon as we achieve this, we will migrate and release language compatibility for J2Store4. We will keep you informed of our progress.

**Comment by mgopin3** [comment]
@ufuk-avcu Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
