### ISSUE TITLE
Translation / en-GB.com_j2store.ini

### ISSUE THREAD

**Issue by schultz-it-solutions** [J2Store4/j2store4#107]
on lines 2253 and 2254, there is one underscore missing in the constant name.

you might want to update this before your next release.
kind regards
Ruediger Schultz

Is there any progress regarding translations? You could setup the respective project on TRANSIFEX for example, to get this going with community collaboration.
I would be willing to help with the german translation (but not alone!)

**Comment by mgopin3** [comment]
@schultz-it-solutions We wish to update you on our current language support, which is currently exclusive to J2Store3. Your feedback is highly valued, and we are diligently working towards extending language support to encompass all countries. Once this goal is achieved, we will promptly transition and provide language compatibility for J2Store4. Stay assured that we will keep you informed of our progress as we continue to enhance our offerings.

**Comment by mgopin3** [comment]
@schultz-it-solutions Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
