### ISSUE TITLE
Invoice template does not translate language strings

### ISSUE THREAD

**Issue by schultz-it-solutions** [J2Store4/j2store4#108]
The invoice template allows to add a table of items with the substitution code  [ITEMS]

This creates a table for all purchased items. 
But: the general language strings are NOT TRANSLATED, they appear like:

J2STORE_ORDER_SUMMARY
J2STORE_CART_LINE_ITEM
J2STORE_CART_LINE_ITEM_QUANTITY
J2STORE_CART_LINE_ITEM_TOTAL
J2STORE_CART_LINE_ITEM_UNIT_PRICE
J2STORE_BACK_ORDER_ITEM

This could be caused by rendering the ITEMS template "too late", when rendering of the language-strings is already done.
I checked, and all the relevant language files are indeed loaded in the respective modal window.

**Comment by schultz-it-solutions** [comment]
Additional note: the same table shows up just fine in the actual order view in the backend. The problem is only with the invoice template.
![2024-04-26_11-31-56](https://github.com/J2Store4/j2store4/assets/8665822/ae0eb2af-267f-4cf5-abec-1e35de2c4056)

**Comment by mgopin3** [comment]
@schultz-it-solutions Thank you for bringing this issue to our attention. Please rest assured that we will address it promptly. We will take note of this matter and ensure that it is resolved in the upcoming J2Store 4.0.5 release. Your understanding and patience are greatly appreciated.

**Comment by mgopin3** [comment]
@schultz-it-solutions Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
