### ISSUE TITLE
Payment method /extentions Multisafe Payment Plugin

### ISSUE THREAD

**Issue by ptrouw** [J2Store4/j2store4#111]
Hi,
I am running 4.0.5 on J4. Where can I find Multisafe Payment Plugin? I want to test if this one is still working with 4.0.5.

**Comment by mgopin3** [comment]
@ptrouw We would like to inform you that the Multisafe Payment Plugin is currently not available for J2Store 4. We are in the process of migrating compatibility for J2Store 4 with Joomla 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing the Multisafe Payment Plugin compatibility for J2Store 4 as soon as possible.

**Comment by mgopin3** [comment]
@ptrouw Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
