### ISSUE TITLE
J2store on joomla 4 plus, paypal plugin

### ISSUE THREAD

**Issue by jeremyfranco** [J2Store4/j2store4#112]
I have updated my site and before i pay for the pro subscription, I need to know how i can integrate with paypal, card payments and or revolute. At present I cannot find compatible options.

I also have an issue as I am road testing your free product. when I go to buy onlilne, the shipping details show address details but when I choose Ireland which is my primary zone, It shows that i need to input  a stse in the USA. I have tried, turning off USA shipping but no good.

Please advise if your product is suitable..

Jeremy

**Comment by jeremyfranco** [comment]
I fixed USA shipping field, however I have no shipping rates as updated from joomla 3. they show on checkout when i previously set up, but i cannot access and change, is this a plugin not available yet in joomla 4 release. thx

**Comment by mgopin3** [comment]
@jeremyfranco I understand your concern. We would like to inform you that the **USA shipping** is currently not available for J2Store 4. We are in the process of migrating compatibility for J2Store 4 with Joomla 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing the **USA shipping** compatibility for J2Store 4 as soon as possible.

**Comment by skaysurfer** [comment]
> I fixed USA shipping field, however I have no shipping rates as updated from joomla 3. they show on checkout when i previously set up, but i cannot access and change, is this a plugin not available yet in joomla 4 release. thx

how do you fixed the usa shipping zones? please advise

**Comment by jeremyfranco** [comment]
I think i disabled, region and zone, but not 100% sure, I understand
j2store is waiting for joomla 4 5 full upgrade??
Jeremy Franco
www.yachtcharterireland.com

**Comment by mgopin3** [comment]
@jeremyfranco Could you please share a video demonstrating the steps to reproduce the issue? This will greatly assist us in resolving the problem on our end.
