### ISSUE TITLE
500 error cannot get modal

### ISSUE THREAD

**Issue by cantgetmyusername** [J2Store4/j2store4#113]
I'm not sure what's throwing this but customers cannot get to their profile. Screenshots.

![Screenshot 2024-06-20 at 8 43 44 AM](https://github.com/J2Store4/j2store4/assets/5192979/66437887-441a-4271-a26b-b55aa5770714)

![Screenshot 2024-06-20 at 8 56 25 AM](https://github.com/J2Store4/j2store4/assets/5192979/ac9099f5-020e-4c6f-ba55-aef17a23170c)

**Comment by cantgetmyusername** [comment]
First screenshot shows a different oddity.

<html><head></head><body>
Web Server | ApacheLinux server.xyonet.dev 6.1.0-13-amd64 #1 SMP  PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
-- | --

- PHP Version | 8.2.20
- Joomla! Version | Joomla! 5.1.1 Stable [ Kudumisha ] 28-May-2024 16:00 GMT
- J2Store Version | 4.0.5Professional
- Memory Limit | 512M
- CURL | Enabled
- JSON | Enabled
- Error Reporting | default
- Cache | Disabled
- Cache System Plugin | Disabled
- Clear cart cron url | https://xxxxxxxxx.org/index.php?option=com_j2store&view=crons&task=cron&cron_secret=a9c346af55e36d3f648994a8aafe1c0f&command=clear_cart&clear_time=1440

</body></html>

![Screenshot 2024-06-20 at 8 57 24 AM](https://github.com/J2Store4/j2store4/assets/5192979/9959d1b1-6f6c-4ea6-88ec-7daec4d1a844)

**Comment by mgopin3** [comment]
@cantgetmyusername We are unable to reproduce this issue on our site. Please share a video reference showing the steps to reproduce this issue.

**Comment by cantgetmyusername** [comment]
I just changed stores - was sorry to do that but it seemed better than a
completely broken website. J2Store is still running on a couple of my
client stores - but now I'm afraid to update.
