### ISSUE TITLE
Editing an a-mailtemplate results in an error

### ISSUE THREAD

**Issue by Kris3D** [J2Store4/j2store4#116]
![image](https://github.com/J2Store4/j2store4/assets/51743129/f1682839-3561-444c-8ed1-ecdcaed193b9)
![image](https://github.com/J2Store4/j2store4/assets/51743129/a4dff32f-3fd6-4b36-a16b-0722b254417d)
Editing an a-mailtemplate results in an error

**Comment by mgopin3** [comment]
@Kris3D I understand your concern, and I assure you that we are actively working to ensure compatibility between our J2Store 4.x.x component and Joomla 5. We are committed to resolving this issue in an upcoming release of J2Store. In the meantime, to address this issue, you can make changes to your /administrator/components/com_j2store/helpers/j2html.php file.

Please locate line number 880 in the j2html.php file and replace the existing code with the following:
**$options = isset($options['buttons']) && is_array($options['buttons']) ? $options['buttons'] : [];
$editor = self::getEditor($editor_type);
$html = $editor->display($name, $value, $width, $height, $cols, $rows, false, $id, null, null, $options);**

By implementing this change, the issue should be resolved. For further guidance, you can refer to the video provided [[video](https://www.awesomescreenshot.com/video/26016156?key=534266cf4a48ef04853ba85a0542a2f5)]

**Comment by Kris3D** [comment]
Yes, Thank you. This worked great.
