### ISSUE TITLE
Feature Request: Make compatible for Joomla 5

### ISSUE THREAD

**Issue by nib-kiag** [J2Store4/j2store4#119]
Joomla 5 is getting very popular, and Joomla 4 EOL is coming closer and closer.
Please make the necessary fixes so J2Store can be used in Joomla 5.
I recently upgraded a website running J2Store 4.0.5 to Joomla 5 (PHP 8.1), and it seems to be running fine, but still throws some 'deprecated' errors/warnings. I can provide you with access to a test installation of this site if it helps.

**Comment by mgopin3** [comment]
@nib-kiag I understand your concern. Currently, we have not tested J2Store 4 compatibility with Joomla 5. Please rest assured that we appreciate your feedback, and we will take note of it. In the near future, we plan to migrate and conduct thorough testing to ensure J2Store 4 is compatible with Joomla 5. This update will be included in an upcoming J2Store release. Thank you for your patience and understanding.

**Comment by TLWebdesign** [comment]
Any ETA on this update?

**Comment by TLWebdesign** [comment]
@nib-kiag have you had any problems running it on J5? besides deprecated warnings?

**Comment by nib-kiag** [comment]
> @nib-kiag have you had any problems running it on J5? besides deprecated warnings?

@TLWebdesign I did not do extensive tests, but everything seemed to work fine. Joomla 5.1.2 with PHP 8.1.30

**Comment by nib-kiag** [comment]
How is this completed? Is there a working version for Joomla 5?

**Comment by TLWebdesign** [comment]
Seems the shipping methods are not showing anymore on J5. Can you confirm? Also yeah where is the j5 compatible version?
