### ISSUE TITLE
Feature to add currency value is broken

### ISSUE THREAD

**Issue by r9guy** [J2Store4/j2store4#122]
When Creating Currency , the field value after hitting save defaults to 1.00.
this is a bug.
![image](https://github.com/user-attachments/assets/da11271e-9a31-475f-8d2d-02e95c5e6c9f)
![image](https://github.com/user-attachments/assets/0aed1fe7-c079-4843-8b91-762c7a48241b)

**Comment by mgopin3** [comment]
@r9guy We would like to inform you that Exchangerate Host has discontinued their free API service for calculating currency exchange rates. If you would like to continue using currency exchange functionality on your site, you can create an account with Exchangerate API or Currency API. After creating an account, you will receive an API key, which you can enter into the Currency Exchange Rates - Google Finance API plugin. Once this is done, you should be able to calculate currency rates without any issues. If you continue to experience problems, please let us know, and we will assist you further.
