### ISSUE TITLE
Additional Fees plugin not working

### ISSUE THREAD

**Issue by metcalfemedia** [J2Store4/j2store4#123]
Hi there, 

I have installed and configured the Additional Fees plugin correctly (I believe, at least), however it just doesn't seem to work. It installs and appears to be loaded fine, the additional fee doesn't apply. Note that I am not a developer, however, I did have someone with extensive J2store experience look into this and they suggested I send this issue in. Can you please look into this? 

J5.1.4
J2store 4.0.5 PRO
PHP 8.3.10

**Comment by mgopin3** [comment]
@metcalfemedia As requested, we have checked your site and can confirm that the Simple CSV Import/Export plugin is working without any issues. For your reference, please check this video:https://www.awesomescreenshot.com/video/31399961?key=8ea11184b4a49a1faa04c4694d8977a4

If you continue to experience the same issue, kindly submit a ticket to our J2Store support team. Please include your admin login details and FTP information. This additional information will greatly assist us in resolving the issue from our end.

**Comment by metcalfemedia** [comment]
I am trying to do a percentage on a line item (per product). I will keep playing with it. I tried to submit a ticket, but the link to subscribe to Pro is a dead link? Also, I wanted to make sure I had the latest version of the plugin and this is not found in the my downloads area of my account.

**Comment by newlinewebdesign** [comment]
@mgopin3 I also tested the plugin and it did not work on a simple product using the product app form. not sure why. Removing $variant_status check in the app_extrafee.php file (~line 532) got it working on the product line item level . Settings used on the product level were all default except 3% on any line item.

**Comment by mgopin3** [comment]
@metcalfemedia If there are any concerns or technical difficulties, you can raise a support ticket by utilizing the email address associated with your purchase. Kindly use [support@j2store.org](mailto:support@j2store.org) for this purpose. This email will ensure efficient resolution and prompt assistance with any inquiries or challenges you may encounter. Thank you for your cooperation.
