### ISSUE TITLE
Disabled Quantity Boxes Still Being Displayed In the Basket

### ISSUE THREAD

**Issue by sdckey** [J2Store4/j2store4#124]
Quantity boxes are still being displayed above the Basket even when disabled in the global J2Store4 global configuration and the store configuration.

![2024-09-12_00-21-34](https://github.com/user-attachments/assets/3f85a5ed-e2df-4860-b433-82fe9f385689)

Thanks.

**Comment by mgopin3** [comment]
@sdckey If there are any concerns or technical difficulties, you can raise a support ticket by utilizing the email address associated with your purchase. Kindly use [support@j2store.org](mailto:support@j2store.org) for this purpose. This email will ensure efficient resolution and prompt assistance with any inquiries or challenges you may encounter. Thank you for your cooperation.
