### ISSUE TITLE
Downloadable product (PDF) in order history is broken after download

### ISSUE THREAD

**Issue by webgras** [J2Store4/j2store4#125]
Hi,
we have updated to the latest versions (J4.4.8 and J2Store 4.0.5)
I have downloadable products with PDF.
File path is set.
You can buy the product.
After payment I can download the PDF, but the PDF is broken.
The file has the correct size, but does not open. the PDF reader says: there is a problem to open the file. When reading the document there is an error (14).
If I download the file through FTP, I can open it without a problem.

can you confirm that issue?
Thanks

**Comment by webgras** [comment]
ok, here you get more information:
https://community.adobe.com/t5/acrobat-reader-discussions/there-was-a-problem-reading-this-document-14/m-p/9208676
If I click ctrl and ok, then I see
"Dict-Object expected"

**Comment by webgras** [comment]
Ah, it seems the PDF is broken. sorry.

**Comment by mgopin3** [comment]
@webgras  I understand your concern. Upon your request, we have thoroughly checked our site, and we can confirm that the downloadable product is functioning without any issues.

In this case, I recommend raising a support ticket using the email address associated with your purchase. Please contact [support@j2store.org](mailto:support@j2store.org) for prompt assistance and resolution of any inquiries or challenges you may encounter.
