### ISSUE TITLE
expiration download link 

### ISSUE THREAD

**Issue by mehdininja** [J2Store4/j2store4#15]
The expiration date of the download link is the current date!

**Comment by mehdininja** [comment]
![InkedScreenshot 2023-08-25 at 01-38-23 _LI](https://github.com/J2Store4/j2store4/assets/74552816/a3c4f1c5-7550-42f8-b0b4-248565ce487a)
access_granted and  access_expires  is null

**Comment by alagesanbe08** [comment]
@mehdininja Please test the fix #16
