### ISSUE TITLE
incompatibility issue

### ISSUE THREAD

**Issue by lushdomain** [J2Store4/j2store4#19]
There is a conflict between J2Store's content plugin and the Joomla page builder pagebuilderCK from Ced at [joomlack.fr](http://joomlack.fr/)
 
According to him .....
 
"I have reproduced the issue by my side, it seems related to the load of their specific field in the form, on the line 48 :
F0FDispatcher::getTmpInstance('com_j2store', 'product', array('layout'=>'form', 'tmpl'=>'component', 'input' => $input))->dispatch();
 
unfortunately this problem is located on the J2store side. 
"
 
Both J2Store and pagebuilderCK use the basic Joomla article to display the new format article.
 
Ced is happy to work with your developers to find a solution. His email is:
 
ced1870@gmail.com
 
I think this is important as both of these components are well recognised and supported by the Joomla community. Failure of these components to play nicely with each other might result in one or other being dropped by users in favor of non conflicting software, which could hurt your business model.
 
Please let me know your stand on this matter.

**Comment by lushdomain** [comment]
Really. No comment yet?

**Comment by mgopin3** [comment]
@lushdomain I appreciate your concern. Regrettably, we have been unable to reproduce the reported issue. To expedite the resolution process, kindly provide a video reference detailing the steps to reproduce the problem. This additional information would be highly valuable in assisting us to identify and address the issue effectively from our end.
