### ISSUE TITLE
Migrator wont work in J4

### ISSUE THREAD

**Issue by landed1** [J2Store4/j2store4#20]
Hi
I am stuck because I upgraded then only saw the instructions for J2store. So I am at j4 with a fully working site apart from j2 store.
All I think I need to do is install a clean install but am blocked as it does a check for the migration plugin. When I install the migration plugin it breaks because I think that only works in J3.

Any way to uninstall them and keep my store data? TY

**Comment by Thomastomy2001** [comment]
Hi landed1 
    Please utilize Joomla 3 site backup to create a new Joomla 3 and J2Store 3 site. Afterward, perform the migration from J2Store 3 to J2Store 4 in Joomla 3 using the J2Migration component. Please review the provided documentation as it contains valuable information to assist with the migration process (https://docs.j2store.org/migration-from-j2store-3-to-4).
    Alternatively, you must set up a new site for J2Store 4 with Joomla 4. Unfortunately, it's not possible to retrieve the old data in this scenario.
