### ISSUE TITLE
J2Store Dashboard: show only completed transactions

### ISSUE THREAD

**Issue by PixedBo** [J2Store4/j2store4#38]
I've noticed that in dashboard statistics i get both paid and unpaid orders summed.

Total of the day:

![today1](https://github.com/J2Store4/j2store4/assets/12549961/cf86013e-22d9-4141-bd7b-652cd0b561cb)

Details of the 2 orders:

![today2](https://github.com/J2Store4/j2store4/assets/12549961/80cfe435-bee1-4515-a362-418467bf32be)

Is possible to have only the completed orders? Because if in the single day I have a lot of people that go to the payment and then cancel the statistics get ruined by non-existent sales.

Thanks

**Comment by mgopin3** [comment]
I understand your concern. To calculate today's earnings specifically for orders with confirmation status, you can follow these steps:

1.Navigate to 'System' > 'Administrator Modules' and search for the 'J2 Store Stats Mini' module.
Inside the 'J2 Store Stats Mini' module, locate the 'Status' option. Select the status (e.g., 'confirmed' or 'processed') for which 2.you want to calculate the total amount displayed on your admin dashboard.
3.Save the changes.
After completing these steps, the total amount will be calculated based on your status selection. You can also refer to this video for guidance:-https://www.awesomescreenshot.com/video/21756290?key=b71d9b1e813fcb9773fd4ee8ceae61dc

**Comment by PixedBo** [comment]
Great, thanks.
Last question: what's the difference between the two modules "store stats" and "store stats mini"?

**Comment by rameshelamathi** [comment]
Please do not post support requests in the issues section. Unfortunately, we do not provide any support via the issues section.
