### ISSUE TITLE
Problem to add manufacturer

### ISSUE THREAD

**Issue by ScaleBxl** [J2Store4/j2store4#42]
Hello 

After migration to J2store 4.0.3 PRO, with Joomla 4.3.4, and PHP 8.1.24 

I have a problem to add manufacturers, have you an solution for that? 

Here is the error message:

**"Field 'address_id' doesn't have a default value"**

Old manufacturers before migration are still there without any problem

Thank you!

**Comment by Thomastomy2001** [comment]
Thank you for bringing this issue to our attention. Please don't worry, we will treat this as valuable feedback. We intend to address and resolve this issue in an upcoming release of J2Store4. You can refer to the commit code changes on J2Store4 for more information https://github.com/J2Store4/j2store4/pull/44

**Comment by ScaleBxl** [comment]
Problem still persist after update to j2store V4.04

**Comment by mgopin3** [comment]
I appreciate your understanding. The reported issue has been addressed and resolved in J2Store version 4.0.4. Upon conducting thorough testing on our site, we have confirmed that the creation of manufacturers is functioning seamlessly.

For your reference, a video demonstrating the successful creation of manufacturers can be viewed [here](https://www.awesomescreenshot.com/video/25515047?key=040daa5cd83d504edb9b414a23bbd268).

In the event that you continue to encounter any challenges, I recommend submitting a support ticket to the J2Store support team. Please include your **admin login** details and **FTP** information for a more efficient resolution from our end.

**Comment by ghadirkiani** [comment]
Problem still persist after update to j2store V4.05

**Comment by mgopin3** [comment]
@ghadirkiani In the event that you continue to encounter any challenges, I recommend submitting a support ticket to the J2Store support team. Please include your **admin** login details and **FTP** information for a more efficient resolution from our end.
