### ISSUE TITLE
Bad product image link

### ISSUE THREAD

**Issue by ScaleBxl** [J2Store4/j2store4#45]
Hello 

Another little problem, when I link product image in category view, instead of 

"MYSITE/products_category/product_xxx" I have this link

"MYSITE/component/j2store/products_category/product_xxx" 
(this one takes me back to the home page every time, instead of the product page)

A solution?

**Comment by ScaleBxl** [comment]
Same problem with : 

- "read more" button to product page 
- with the link (text) and image link of up sells and cross sells products

**Comment by mgopin3** [comment]
I appreciate your understanding. Thank you for bringing this issue to our attention. Please rest assured that we will treat it as valuable feedback, and we are committed to resolving this matter in the upcoming J2Store4 release. For your reference, please review the code changes in commit #47 on J2Store4.

**Comment by ScaleBxl** [comment]
Problem resolved ! Great work ! Thank you
