### ISSUE TITLE
Mollie plugin version 1.32

### ISSUE THREAD

**Issue by MartijnMaandag** [J2Store4/j2store4#48]
I am using Mollie plugin 1.29. 
When I publish it it turns off again. J2Store says there is a version 1.32.
Can I have a link where I can download this release?

**Comment by mgopin3** [comment]
Just to confirm, are you using Joomla 4 with J2Store 4 for your site? If yes, Mollie payment plugin version 1.32 or below is not compatible with J2Store 4. As a result, when you go to the J2Store 4 dashboard, the unsupported plugin will be disabled automatically.

Currently, we have migrated and released Mollie payment plugin version 4.0.0, which is compatible with J2Store 4. If you would like to use the latest version of the Mollie plugin (version 4.0.0) for your J2Store 4 site, please use the link above to purchase the latest release:- https://www.j2store.org/downloads/mollie/

**Comment by MartijnMaandag** [comment]
Thanks
