### ISSUE TITLE
Something wrong?

### ISSUE THREAD

**Issue by ScaleBxl** [J2Store4/j2store4#51]
I have a menu link to a "Blog" page where there are no products, and yet I have a price wandering around, and if I activate the store it of course becomes a cart button.
![Sans-titre-1](https://github.com/J2Store4/j2store4/assets/149295599/21050085-2004-443c-972d-c98bcdf67dfe)

**Comment by ScaleBxl** [comment]
This price remains displayed even if I deactivate all products!

**Comment by mgopin3** [comment]
I understand your concern. Upon checking our site, we found that when creating a new product and including it in the blog menu, the product displayed correctly without any issues. Additionally, after deactivating the product, the price was appropriately hidden.

To assist you further, we have prepared a video for your reference: [[video link here](https://www.awesomescreenshot.com/video/22880930?key=4bf2c11aa3273971f9a55fbe4e919741)]

If you are still experiencing the issue, I recommend following these steps to hide the price on your blog menu:

Step 1: Navigate to J2Store -> Setup -> Configuration.
Step 2: In the Product tab, scroll down to find the "Show price" option and set the value to "No."
Step 3: Save the changes.

Completing these steps should resolve the issue. Please let us know if you encounter any further difficulties.

**Comment by ScaleBxl** [comment]
Problem resolved !

Thank you ;)
