### ISSUE TITLE
Payfast payment gateway disables after navigating away. 

### ISSUE THREAD

**Issue by bugser** [J2Store4/j2store4#59]
![image](https://github.com/J2Store4/j2store4/assets/153738692/09a49b8d-6df0-4a79-a4f1-2a6e07d71486)

**Comment by mgopin3** [comment]
I understand your concern. 
We would like to inform you that currently, the "Pay fast" payment plugin is not compatible with J2store4. As a result, it will be disabled automatically. Please don't worry about this,we have taken note of your request, and we will prioritise migrating this plugin for compatibility with Joomla 4 and J2store4 as soon as possible.

**Comment by bugser** [comment]
Thank you for your fast reply, please keep me posted as I will be losing revenue the longer this plugin doesn't work.  Any other compatible payment plugin that supports Zar currency?

**Comment by mgopin3** [comment]
Thank you for your prompt response. I understand the urgency, and I share your concern about potential revenue loss. If you're looking for an alternative payment plugin that supports the Zar currency, I recommend trying our Stripe Checkout payment plugin. It is compatible with Zar currency, and we have tested it successfully on our site.

I suggest installing the plugin on your test site to configure it with Zar currency and conduct a test order. If it meets your requirements, you can confidently proceed with it. We assure you that we have verified its functionality with the same configuration on our site, and it worked seamlessly without any issues.

For your reference, please review the Stripe currency supported documentation:-https://stripe.com/docs/currencies. You can purchase the latest release of our Stripe Checkout plugin, compatible with Joomla 4 and J2Store 4, by following this link: [[purchase link](https://www.j2store.org/downloads/stripe-checkout/)]

**Comment by tangotea** [comment]
Hi Mgopin3 you can imagine that I don't want to pay for a stripe plugin when I have already spent money on a Payfast plugin.  This error is not on my side and I am wasting a lot of time and revenue for a plugin that doesn't work.  The Stripe plugin, although it supports ZAR is not available in South Africa unless you have a US company.   When will you fix this Payfast issue, it is urgent and 3 weeks have already past.

**Comment by mgopin3** [comment]
Thank you for your patient waiting. We would like to inform you that we have successfully migrated and released the PayFast payment plugin with compatibility for J2Store4 and Joomla 4. If you wish to integrate our latest release, PayFast Plugin version 4.0.0, on your site, kindly utilize the provided link for the purchase. 

Here is the link to acquire our latest PayFast plugin release: [[purchase link](https://www.j2store.org/downloads/payfast/)]

**Comment by tangotea** [comment]
I am not going to purchase a plugin I purchased before. This should not cost me anything.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mgopin3** [comment]
@tangotea Upon reviewing our live development site, we have confirmed that the Payfast plugin functions seamlessly with the ZAR currency when purchasing a product. For your reference, please view this video: [[video](https://www.awesomescreenshot.com/video/25483378?key=4f99bae593025860817f32fc4fedc876)].

In this context, I recommend sharing a video reference detailing the steps to reproduce the issue. This will greatly assist us in comprehending and resolving the matter from our end.

**Comment by bugser** [comment]
I paid a developer to fix it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
