### ISSUE TITLE
Zones on checkout page are not being loaded when Joomla is set to use URL rewriting

### ISSUE THREAD

**Issue by Stanzi1791** [J2Store4/j2store4#61]
I've installed J2Store version 4.0.4 pro in a fresh Joomla 4.4.1 installation.

For J2Store I then did the minimum to get it working: filled out the store information, added the J2Store Products List View to the Main Menu and created a new Article/product.

If I now go to the frontend of the site, add a product to my cart, go to checkout and log in,
I can select a different country on the checkout page and the corresponding zones are loaded.

Now for the problem:

I then enable "Use URL Rewriting" under Joomla administrator > System > Global Configuration > Site tab
and rename the htaccess.txt in Joomla's root directory to .htaccess (as it says I should).

If I now go back to the site index and then back to checkout (this is important because now the checkout uses the new url without `index.php` in it), it no longer loads the corresponding zones when I change the country.

When I inspect the console it says it can't find this url:
`http://localhost/j2store/component/j2store/index.php?option=com_j2store&view=carts&task=getCountry&country_id=209&_=1702644983030 404 (Not Found)`

It looks like the loading of the zone list is not working properly with Joomla's URL rewriting.
Am I doing something wrong, did I miss a setting, is there a fix available or a workaround I can use?

(Joomla 5.0.0 with J2Store 4.0.4 pro installed and URL rewriting enabled seems to have the same problem.)

Kind regards,
Marleen

**Comment by mgopin3** [comment]
I understand your concern. Upon reviewing the error code, it appears that you have not created a Checkout menu on your site. Consequently, you are facing this issue. In this case, I recommend creating a Checkout menu on your site. After completing these steps, the issue should be resolved. We have also verified and reproduced this issue on our site, and after creating the Checkout menu, the problem was resolved. For your reference, please view this instructional video: [[video link](https://www.awesomescreenshot.com/video/23373468?key=56b0b74a84c68395ebc03893ca2309b2)].

**Comment by Stanzi1791** [comment]
Thank you for your reply.
Your solution does work, but I'd rather not have an extra "checkout" menu item.

The problem seems to be that the ajax request is being sent to an `index.php` page relative to the "current" url, and with url rewriting enabled, the "current" url looks like it contains subfolders, so it then looks for this `index.php` file inside of these subfolders (which don't exist).

So the ajax request that now gets sent to `http://localhost/j2store/component/j2store/index.php?option=com_j2store&view=carts&task=getCountry&country_id=209&_=1702644983030` should have been sent to `http://localhost/j2store/index.php?option=com_j2store&view=carts&task=getCountry&country_id=209&_=1702644983030` instead.

I've now fixed it with an additional line in the Joomla `.htaccess` file:

```
	## Begin - Custom redirects
	#
	# If you need to redirect some pages, or set a canonical non-www to
	# www redirect (or vice versa), place that code here. Ensure those
	# redirects use the correct RewriteRule syntax and the [R=301,L] flags.
	#

	RewriteRule ^component/j2store/index\.php(.*)$ index.php$1 [R=301,L]

	## End - Custom redirects
```

It looks like this is working too, but I'm not sure if it doesn't break anything else.
Leaving this here in case anyone else also runs into the same problem.

Kind regards,
Marleen

**Comment by Stanzi1791** [comment]
Thank you for your reply.
Your solution does work, but I'd rather not have an extra "checkout" menu item.

I've now fixed it with an additional line in the Joomla `.htaccess` file:

```
	## Begin - Custom redirects
	#
	# If you need to redirect some pages, or set a canonical non-www to
	# www redirect (or vice versa), place that code here. Ensure those
	# redirects use the correct RewriteRule syntax and the [R=301,L] flags.
	#

	RewriteRule ^component/j2store/index\.php$ /index.php [R=301,L]

	## End - Custom redirects
```

It looks like this is working too, but I'm not sure if it doesn't break anything else.

Kind regards,
Marleen

**Comment by mgopin3** [comment]
@Stanzi1791 I appreciate your concern. Typically, creating a checkout menu resolves this issue. However, if you prefer not to create a checkout menu immediately, you can alternatively attempt to include a redirect path in the .htaccess file. Verify if this resolves the issue for you, and if successful, you may proceed with this solution. We hope this option proves satisfactory for you.

**Comment by mgopin3** [comment]
@Stanzi1791 We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by Stanzi1791** [comment]
The addition to the `.htaccess` seems to have solved the problem, so this issue can be closed.
Thanks for your help!
