### ISSUE TITLE
Bad product link in Product Module

### ISSUE THREAD

**Issue by ScaleBxl** [J2Store4/j2store4#63]
Hello

Another little problem, with product links in product module, instead of

"MYSITE/products_category/product_xxx" I have this link

"MYSITE/component/j2store/products/product_xxx"

(this one takes me back to the home page every time, instead of the product page)

A solution?

**Comment by mgopin3** [comment]
I understand your concern. We have checked and confirmed that on our site, the product link redirects to the product page in the product display module without any issue. For your reference, please review this video [[video link](https://www.awesomescreenshot.com/video/23374147?key=00cc0c1ea8d500620354369afed7022b)]. If you continue to experience the same issue, kindly share the video reference to help us reproduce the problem.

**Comment by ScaleBxl** [comment]
Take a look
[Bienvenue_sur_-_Made_in_Asturies_—_Mozilla_Firefox_2023-12-18_11-06-15.webm](https://github.com/J2Store4/j2store4/assets/149295599/77c50ca7-f25d-40a4-8a62-dcabf864705d)

**Comment by ScaleBxl** [comment]
[Bienvenue_sur_-_Made_in_Asturies_—_Mozilla_Firefox_2023-12-19_13-31-55.webm](https://github.com/J2Store4/j2store4/assets/149295599/89ec8a1f-e5fb-4181-ae0d-d69795677962)

**Comment by mgopin3** [comment]
Thank you for your patience. After reviewing the video reference, it appears that you are using multiple languages on your site. In this case, you need to create the same product for each language used on your site. Typically, when you click on a product in the product display module, if there is a product available in that language, it will redirect to the respective product page. If not, it will redirect to the home page. Please make sure to create a product for each language.After completing this, the issue will be resolved.

**Comment by ScaleBxl** [comment]
Hello 

Thank you for your reply, but I have a product for each language and product module in each language too.

**Comment by ScaleBxl** [comment]
Another solution?

**Comment by ScaleBxl** [comment]
[Modules_(Site)_-_Made_in_Asturies_-_Administration_—_Mozilla_Firefox_2024-01-04_13-21-53.webm](https://github.com/J2Store4/j2store4/assets/149295599/cfee58cf-9113-4414-b644-ceebbdea3087)

Products in 4 languages :
![products](https://github.com/J2Store4/j2store4/assets/149295599/9b56b03e-20eb-4a89-930f-bb0d95a1d8fa)

Articles where I'm using the product_module
![articles](https://github.com/J2Store4/j2store4/assets/149295599/62075533-e7b7-4b9b-ba9b-852bc5ef3404)

Modules in 4 languages
![modules](https://github.com/J2Store4/j2store4/assets/149295599/a3183c73-7985-4b74-88fc-0a80fb93cf25)

**Comment by ScaleBxl** [comment]
ok I think the best thing to do is to do without your module !

**Comment by mgopin3** [comment]
I appreciate your attention to detail. Upon reviewing the referenced video, it appears that you have developed individual modules for each language and corresponding products. To enhance user experience, it is imperative to establish a dedicated menu for each language, wherein the associated products will be displayed. In the absence of a language-specific menu, clicking on a product within a module will trigger a search within the corresponding language menu. If the product is found, it will seamlessly redirect to the respective product page; otherwise, redirection to the home page will occur. I trust this explanation clarifies the necessary steps for optimal functionality.

**Comment by ScaleBxl** [comment]
Sorry but I don't understand !

I have a 1 main menu where there is the products link for each language. Can't this link be in my main menu?

![Sans-titre-1](https://github.com/J2Store4/j2store4/assets/149295599/10d6c68a-6419-4e02-91e6-bdc6428cb9fd)

**Comment by ScaleBxl** [comment]
Given the lack of support, I am giving up using J2store for all my new projects, you are no longer up to date :(

I have 3 projects to update and I can't do it and I don't dare anymore.
I have a new project with dateline and I can't move forward,

You do your best, I understand that but it's not enough.
Sorry but I'm looking for another online store solution.

**Comment by mgopin3** [comment]
@ScaleBxl Thank you for your patience.
Ensure that you have created a main menu for each specific language. Under the respective main menu, add the specific language category products. Upon completion of these steps, the product should redirect to the product page without any issues.

If you continue to experience the same issue, kindly submit a ticket to our J2Store support team. Please include your admin login details and FTP information. This additional information will greatly assist us in resolving the issue from our end.
