### ISSUE TITLE
EU VAT plugin. VIES Validation not working on J2Store 4.0.4

### ISSUE THREAD

**Issue by niky94547** [J2Store4/j2store4#73]
Hello,

  We have an installation of Joomla-3.10.12 with J2store-3.3.20 Core.  On that installation EU VAT check plugin/app operated as expected, we receive real time VIES validation.  But once we upgrade to J2store 4.0.4 Pro, EU VAT check no operating anymore.

Thanks on your support,

Kind Regards,

**Comment by mgopin3** [comment]
I understand your concern. We would like to inform you that the **EU VAT**  app is currently not available for J2Store 4. We are in the process of migrating compatibility for J2Store 4 with Joomla 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing the **EU VAT**  app compatibility for J2Store 4 as soon as possible.
Before submitting a report on issue tracker #60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by Rumen33** [comment]
Can you support on this please. I am facing the same problem and need a solution asap. The build in EU VAT validator is one of the best features of your project and the actual reason I choose to use j2store.

**Comment by mgopin3** [comment]
@Rumen33 I appreciate your concern.
Our team is diligently working on the migration process to ensure compatibility with Joomla 4. Rest assured, addressing this matter holds high priority for us, and we are actively engaged in expediting the migration and subsequent release of the EU VAT app for J2Store 4. Your patience is highly valued, and we aim to provide this compatibility at the earliest opportunity.

**Comment by mgopin3** [comment]
@Rumen33 Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by webgras** [comment]
@mgopin3 I need the EU VAT ID plugin but cannot find it in the store. Do you have any update about that topic?
