### ISSUE TITLE
Creating Coupon with limited Date bug

### ISSUE THREAD

**Issue by coolcat-creations** [J2Store4/j2store4#81]
When creating a coupon with a limited time span an error appears:

Call to a member function format) on bool

**Comment by mgopin3** [comment]
After investigating your concern, we tested the creation of a coupon with a limited time span and applied it to a specific product. During the testing process, we confirmed that the coupon was functioning as expected. The coupon amount was calculated without any issues.

For your reference, we have created a video demonstrating the successful application of the coupon. You can view the video here:-  [[video link]( https://www.awesomescreenshot.com/video/25044852?key=d5448854b0b4691ec5a66e408cfc1afe)].

Please let us know if there are any specific steps or scenarios you would like us to further investigate. We are committed to ensuring a seamless experience for you.

**NOTE:-** Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/46, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by coolcat-creations** [comment]
Hello @mgopin3 I checked the error and can reproduce that in German backend language It still does **not** work. It seems to only work with English backend.

**Comment by mgopin3** [comment]
@coolcat-creations We have ensured that the coupon is being created and applied without any issues. In this case, I suggest you kindly share a video reference outlining the steps to reproduce the issue. This would greatly assist us in resolving the issue from our end.

**Comment by coolcat-creations** [comment]
Hi mgopin, here is the video with the evidence. It only happens with german language in backend, with english it works. Thanks for you further investigation.

https://vimeo.com/919067914/a1db4c64af

**Comment by mgopin3** [comment]
@coolcat-creations 
Thank you for the video. We have changed our site to the German language and tested it by creating a coupon, ensuring that it is being created and applied without any issues. In this case, we suggest that you please raise a ticket with the J2Store support team, providing admin login details along with FTP access. This will enable us to better understand and resolve the issue from our end.
