### ISSUE TITLE
Product Compare and Social Media Apps

### ISSUE THREAD

**Issue by JoomFX** [J2Store4/j2store4#84]
Hey guys,

Currently the Product Compare and Social Media Apps are not compatible with Joomla 4/5.
When do you think you will have their updated version released?

![j2store-apps](https://github.com/J2Store4/j2store4/assets/7753940/596d95b7-f7e5-4383-9459-11c0f5f365cc)

**Comment by mgopin3** [comment]
I understand your concern. We would like to inform you that the **product compare** and **social media** is currently not available for J2Store 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing those apps compatibility for J2Store 4 as soon as possible.

**Note:-** Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.
