### ISSUE TITLE
problems in the inventory section

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#95]
Hello and don't be tired to the builders of the j2store
One of the problems I encountered and I think it is better to fix this part in the new updates is the inventory part.
These problems can be seen in this part
**1-** You cannot search by product name
**2-** It would be great if it is possible to search based on product inventory, so you can see the products that are running out here.
**3-** To change the product status, the page is refreshed after saving, and it is not possible to edit several products at the same time
**Suggestion 1**: I suggest that the change in each product should be done in the form of Ajax in such a way that several products can be edited at the same time.
**Suggestion 2**- It is possible to be able to apply the update of all the edits at once by clicking on a button after general editing on several products at the same time.
Important :
If you have a store with a large number of products, this section will not be of much use to you because it has major flaws that need to be updated.
For example, you won't be able to edit 100 products unless the page is refreshed 100 times, which would be very time-consuming and difficult to manage.
**Thanks**

**Comment by mgopin3** [comment]
@sajadsheikhy I understand your concern. Please don't worry about it. In this case, we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. We appreciate your understanding.

**Comment by sajadsheikhy** [comment]
thanks for your support
god bless you

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
