### ISSUE TITLE
Free/gift item in j2store 

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#96]
Suppose we have a product that we intend to give to the customer as a gift if the customer buys it.
**for example :**
We have two products, a laptop, a laptop bag and a mouse
If a customer buys a laptop, we give him a bag and a mouse as a gift
**Note:** All 3 products are available in the store and have a price
When the customer adds the laptop to the shopping cart, the laptop bag and mouse will also be added to the shopping cart at a price of 0 and as a gift.
There is really no place for such a possibility or extension in the store
**### Does the development team have plans for such a possibility?**

**Comment by mgopin3** [comment]
@sajadsheikhy We understand your concern. Currently, we do not have the functionality to support 'buy x, get y' promotions, nor do we offer any apps to meet this specific requirement. However, please rest assured that we acknowledge your request. We will take note of your requirements and consider adding this feature in an upcoming release of J2Store. Thank you for bringing this to our attention, and we appreciate your understanding.
**Note:-** Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by sajadsheikhy** [comment]
thanks

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
