### ISSUE TITLE
Defaulting an option value in option section on the j2store

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#98]
Suppose we have a product that has time guarantees
**for example with option value :**
One month/3 months/6 months/one year
And it is free for one month respectively
And three months, six months and one year are not free
Anyway, the customer has a free one-month warranty for every product he buys, so it is better to choose an option value by default, **for example**, one-month free warranty option value.
Another use of this possibility is to suppose that we have a product where the selection of an option value  is mandatory and must be selected in advance
In this case, we assume an option and it is selected by default
### This defaulting should have two modes
**1- Defaulting in options management and when defining options value
2- defaulting when adding to the product (which in this case will be defaulted only for this product)**
### Thanks to the store development and support team

**Comment by mgopin3** [comment]
@sajadsheikhy If you intend to showcase options like **'Free trial/One month/3 months/6 months/one year'**, you have the option to create and incorporate this feature into your product by setting default values, ensuring it is a required field. For additional guidance, we encourage you to refer to our documentation: [[link](https://docs.j2store.org/catalog/options/how-to-create-options-and-add-them-to-your-products)],Here is the image reference: (https://tinyurl.com/23tzolnz) and (https://tinyurl.com/28jtg5o3)

**Comment by sajadsheikhy** [comment]
thanks for your replay 
link of pictures not open 
(https://tinyurl.com/28jtg5o3)
(https://tinyurl.com/23tzolnz) 
I think you did not understand exactly what I meant
I mean how can I default an option value!
Suppose we have an option with 3 option values
1, 2, and 3, how can we make number 3 be selected by default
regards

**Comment by mgopin3** [comment]
@sajadsheikhy To set the default value for an option, please follow these steps:

1.Navigate to J2store -> Catalog -> Products and select the desired product.
2.Inside the J2store cart, go to the Options tab.
3.Here, you will find the product options you've configured. Click on the "Set Option Values" option.
4.Refer to this image for guidance: [image](https://tinyurl.com/2aj9zled).
5.Once you've generated the option values, navi the igate to the "Default" column.
6.In this column, select the default option you wish to set. You can refer to this image for assistance: [image](https://www.awesomescreenshot.com/image/47069763?key=11f6ce7610f07c0c6275b41906c347af).
Hope you understand.

**Comment by sajadsheikhy** [comment]
Thanks so much 
But my j2 store not have default column in this section 
Please see attach picture
![IMG_4039](https://github.com/J2Store4/j2store4/assets/147089574/a11feaef-2e6a-44da-b0f8-94208462d103)
![IMG_4040](https://github.com/J2Store4/j2store4/assets/147089574/10606509-55f7-41d0-bf14-3c4d6cb4cd9b)
Best regards

**Comment by mgopin3** [comment]
@sajadsheikhy We regret to inform you that, at present, there is no option available to set a default value for a product in J2Store3. The feature to set default options is only supported in J2Store4. We appreciate your understanding in this matter.

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by sajadsheikhy** [comment]
> @sajadsheikhy We regret to inform you that, at present, there is no option available to set a default value for a product in J2Store3. The feature to set default options is only supported in J2Store4. We appreciate your understanding in this matter.

Hello
My j2 store version is version 4.0.4 and not 3, but even though it is version 4, it does not have this option

**Comment by sajadsheikhy** [comment]
Check picture please 
![image](https://github.com/J2Store4/j2store4/assets/147089574/96736145-427f-4dae-abbc-13d28e3962cf)

**Comment by mgopin3** [comment]
@sajadsheikhy We would like to inform you that, at present, we do not have an option to display the default option field for configurable and variable products. Our system currently supports displaying default options only for simple products. However, we have duly noted your requirement and intend to incorporate it into a forthcoming release of J2Store. Thank you for bringing this to our attention.

**Comment by mgopin3** [comment]
@sajadsheikhy  Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
