### ISSUE TITLE
Adding the amount of the option in the price increase mode as a percentage on the j2store option

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#99]
Suppose we have a product that is in an option that the customer is going to pay an extra amount by choosing it.
In the current state, this amount can only be added or subtracted from the total price
For example, we have a laptop that, if the customer chooses a warranty, 10% will be added to the price of the laptop
Currently, this is not possible in the j2store, and you can only add or subtract an amount, and I suggest that this amount be added as a percentage in two ways.:
### 1- Addition to the product price (the price of the product itself and not the selected options)
2- In addition to the finished price of the product with all options
This part needs an explanation
For example, we have a laptop with a price of 1000 dollars, and 10% for its warranty is 100 dollars
Now the customer has upgraded the purchase of some parts and the total price has become 1500 dollars, considering that these parts are also added to the main product, so these parts will also be included in the warranty, and it cannot be said that only the basic product will include the warranty.
I hope you understand
**Thanks to the strong j2store team**
![3](https://github.com/J2Store4/j2store4/assets/147089574/2d4d4e5f-088c-4baa-b90e-5db565cc1e53)

**Comment by mgopin3** [comment]
@sajadsheikhy  I understand your concern. Currently, our J2Store component only allows for adding and subtracting variant option prices with the product's base price. Unfortunately, we don't have the functionality to calculate percentages based on the product price. It's important to note that J2Store is provided free of charge, and as such, we do not offer custom development or support for additional features.

Our current focus is on migrating all plugins to be compatible with J2Store4. However, we appreciate your feedback, and we will certainly consider incorporating this feature into future releases of J2Store. Thank you for bringing this to our attention.

**Note:-** Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
